places = [{"placeName":"Doge's Palace","descrip":"This gothic-style palace is the seat of the Venetian government.","latitude":45.43424,"longitude":12.33805},
{"placeName":"Colosseum","descrip":"The Colosseum was undergoing renovations when I visited.","latitude":41.88998,"longitude":12.49426},
{"placeName":"Vatican Museum","descrip":"I did not have tickets to enter the Vatican, but the Vatican Museum surpassed my expectations.","latitude":41.90219,"longitude":12.45818},
{"placeName":"Naples Archeological Museum","descrip":"This museum contained a piece I had set out to see at the beginning of my trip: The Sappho Fresco.","latitude":40.853088,"longitude":14.25071},
{"placeName":"Casa di Octavius Quartio","descrip":"This home, located in Pompeii, was destroyed in 79 AD with the eruption of Mt. Vesuvius. ","latitude":40.74918,"longitude":14.50074},
{"placeName":"Lido de Jesolo","descrip":"This is the beach area of the Jesolo commune, just outside of Venice.","latitude":45.50796,"longitude":12.644647},
{"placeName":"Ai Do Dai","descrip":"This Venetian restaurant contained many ornate masks.","latitude":45.43451,"longitude":12.33774},
{"placeName":"Murano Glassblowing","descrip":"We visited here and witnessed some amazing glassblowing.","latitude":45.434908,"longitude":12.337308},
{"placeName":"Uffizi Gallery","descrip":"This museum contains works from Botticelli, Michaelangelo, da Vinci and Caravaggio.","latitude":43.76779,"longitude":11.25531},
{"placeName":"St. Peter's Basilica","descrip":"This Renaissance-era basilica is a short walk away from the Vatican.","latitude":41.90216,"longitude":12.45393},
{"placeName":"San Gimignano","descrip":"This hilltop town contains 14 towers, many of which in the medieval style.","latitude":43.46299,"longitude":11.04177},
{"placeName":"Enoteca Properzio","descrip":"We went wine-tasting here.  Truffles, cheese, bread and strawberries filled the air and plates.","latitude":42.99022,"longitude":12.67182},
{"placeName":"Parco Regionale dei Monti Lattari","descrip":"This was a beautiful hiking destination in Campania.","latitude":40.66696,"longitude":14.53333},
{"placeName":"Piazza Dante","descrip":"We tredged in the rain among the fascistic architecture in this Naples public square.","latitude":40.84887,"longitude":14.24984},
{"placeName":"Trevi Fountain","descrip":"The beautiful Baroque Trevi Fountain was breathtaking in person. ","latitude":41.90103,"longitude":12.48332},
{"placeName":"Spiaggia Arenili di Ponente","descrip":"This beautiful beach was the first destination on my trip.","latitude":44.14398,"longitude":8.27582},
{"placeName":"Piazzo San Marco","descrip":"This was the town center in Venice.  About a year after I visited, this area was completely flooded.","latitude":45.43417,"longitude":12.33847},
{"placeName":"Sasso Marconi","descrip":"We passed through this commune town on our way to Florence.","latitude":44.39854,"longitude":11.2493},
{"placeName":"Florence Cathedral","descrip":"This cathedral was perhaps my favorite.  The beautiful red dome is hard to miss in Florence.  Thank you Brunelleschi.","latitude":43.77318,"longitude":11.25595},
{"placeName":"Pantheon","descrip":"When I visited,  rain trickled through the oculus like I was in Assassin's Creed.","latitude":41.89867,"longitude":12.47688}]
